apps/accounts/urls.py
from django.urls import path, reverse_lazy
from django.contrib.auth import views as auth_views
from accounts.views import ProfileView, UserSignUpView, UserActivateView

app_name = 'account'


urlpatterns = [
    path('profile/', ProfileView.as_view(), name='profile'),
    path('password_change/', auth_views.PasswordChangeView.as_view(
        template_name='registration/password_change.html',
        success_url=reverse_lazy('account:profile')
    ), name='password_change'),
    path('regist/', UserSignUpView.as_view(), name='regist'),
    path('activate/<uuid:unique_id>/', UserActivateView.as_view(), name='activate'),
]

root/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.views.generic import TemplateView
from django.conf import settings
from django.conf.urls.static import static
from rest_framework import permissions
from drf_yasg.views import get_schema_view
from drf_yasg import openapi


schema_view = get_schema_view(
    openapi.Info(
        title="Grynevych API",
        default_version='v1',
        description="Home Works",
        terms_of_service="https://www.google.com/policies/terms/",
        contact=openapi.Contact(email="grynevych89@gmail.com"),
        license=openapi.License(name="by Grynevych"),
    ),
    public=True,
    permission_classes=[permissions.AllowAny],
)

v1_url_patterns = [
    path('v1/api/currency/', include('currency.api.v1.urls')),
    path('v1/api/source/', include('source.api.v1.urls')),
    path('v1/api/contacts/', include('contacts.api.v1.urls')),
]


urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls')),

    path('__debug__/', include('debug_toolbar.urls')),

    path('rates/', include('currency.urls')),
    path('source/', include('source.urls')),
    path('contacts/', include('contacts.urls')),

    path('api/', include('accounts.api.urls')),
    re_path(r'^swagger(?P<format>\.json|\.yaml)$', schema_view.without_ui(cache_timeout=0), name='schema-json'),
    re_path(r'^swagger/$', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
    re_path(r'^redoc/$', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc'),

    path('', TemplateView.as_view(template_name='index.html'), name='index'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += v1_url_patterns

templates/layouts/base.html
<!doctype html>
{% load static %}
<html lang="uk">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    {# <link rel="stylesheet" href="{% static 'css/main.css' %}">#}
    <title>Grynevych Mykola - {% block title %}{% endblock %}</title>
</head>

<body>
{% include 'layouts/header.html' %}

<div class="container">
    {% block content %}
    {% endblock content %}
</div>

{% include 'layouts/footer.html' %}

<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js"
        integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js"
        integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF"
        crossorigin="anonymous"></script>
</body>
</html>

templates/layouts/footer.html
<footer>
    <div class="container">
        <footer class="py-3 my-4">
            <ul class="nav justify-content-center border-bottom pb-3 mb-3">
                <li class="nav-item"><a href="{% url 'index' %}" class="nav-link px-2 text-muted">Главная</a></li>
                <li class="nav-item"><a href="{% url 'rate-list' %}" class="nav-link px-2 text-muted">Rates</a></li>
                <li class="nav-item"><a href="{% url 'source-list' %}" class="nav-link px-2 text-muted">Sources</a></li>
                <li class="nav-item"><a href="{% url 'contact-list' %}" class="nav-link px-2 text-muted">Contacts</a></li>

            </ul>
            <p class="text-center text-muted">Copyright: &copy; Grynevych Mykola - Kyiv, 2023</p>
        </footer>
    </div>
</footer>

templates/layouts/header.html
<div class="container">
    <header class="d-flex flex-wrap align-items-center justify-content-center justify-content-md-between py-3 mb-4 border-bottom">
        <ul class="nav col-6 col-md-auto mb-2 justify-content-center mb-md-0">
            <li><a href="{% url 'index' %}" class="nav-link px-2 link-secondary">Главная</a></li>
            <li><a href="{% url 'rate-list' %}" class="nav-link px-2 link-dark">Rates</a></li>
            <li><a href="{% url 'source-list' %}" class="nav-link px-2 link-dark">Sources</a></li>
            <li><a href="{% url 'contact-list' %}" class="nav-link px-2 link-dark">Contacts</a></li>
        </ul>

        <div class="col-md-6 text-end">
            {% if not request.user.is_authenticated %}
                Hi, Guest!
                <a class="btn btn-primary" href="{% url 'login' %}" role="button">Логин</a>
                <a class="btn btn-primary" href="{% url 'account:regist' %}" role="button">Регистрация</a>
            {% else %}
                Hi, {{ request.user.username }}!
                <a class="btn btn-primary" href="{% url 'account:profile' %}" role="button">Profile</a>
                <a class="btn btn-primary" href="{% url 'account:password_change' %}" role="button">Password Change</a>
                {% if user.is_superuser %}
                    <a class="btn btn-primary" href="/admin" target="_blank" role="button">Admin Panel</a>
                {% endif %}
                <a class="btn btn-primary" href="{% url 'logout' %}" role="button">Logout</a>
            {% endif %}
        </div>
    </header>
</div>

templates/layouts/pagination.html
{% if is_paginated %}
    <nav aria-label="Page navigation example">
        <ul class="pagination">
            {% if page_obj.has_previous %}
                <li class="page-item"><a class="page-link" href="?page=1&{{ filter_pagination }}">&lt;&lt;</a></li>
                <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}&{{ filter_pagination }}">&lt;</a></li>
                <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}&{{ filter_pagination }}">{{ page_obj.previous_page_number }}</a></li>
            {% endif %}


            <li class="page-item active"><a class="page-link">{{ page_obj.number }}</a></li>


            {% if page_obj.has_next %}
                <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}&{{ filter_pagination }}">{{ page_obj.next_page_number }}</a>
                </li>
                <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}&{{ filter_pagination }}">&gt;</a></li>
                <li class="page-item"><a class="page-link" href="?page={{ page_obj.paginator.num_pages }}&{{ filter_pagination }}">&gt;&gt;</a></li>
            {% endif %}
        </ul>
    </nav>
{% endif %}